#Nodejs image for the base
FROM node:20-alpine

#Sets ennviornent varable to production, many packages check this to optimize for production
ENV NODE_ENV=production

#Set working directory inside the container (can name it what i want, backend in this case)
RUN mkdir /backend
WORKDIR /backend

#Copy package.json and package-lock.json (all files  in directory that match the package*.json)
COPY package*.json ./

#Install dependencies (skips dev dependencies)
RUN npm install --production

#Copy all source code into container
COPY . .

#Port the backend runs on
EXPOSE 8080

#Command to start the app
CMD ["npm", "start"]

#creates img
#docker build -t practimate-backend .

#runs img with env file
#docker run --env-file .env -p 8080:8080 practimate-backend 