export interface QuestionsData {
    id: string;
    sessionId: string;
    userId: string;
    question: string;
    ispreloaded: boolean | null;
    isautogenerated: boolean | null;
    isprovided: boolean | null;
    createdat: string;
    updatedat: string | null;
    deletedat: string | null;
}